Advanced task and workflows 'apply' command
uselagoon/lagoon-cli pull request #210
Opened 2021-12-08 16:23 UTC by timclifford

# Checklist
- [ ] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated.
- [ ] Changelog entry has been written

Explain the **details** for making this change. What existing problem does the pull request solve?

# Changelog Entry

# Closing issues
possibly #233 (TBC)

2021-12-08 21:22 UTC, shreddedbacon requested changes

2021-12-08 21:22 UTC, shreddedbacon commented on cmd/apply.go
> +						fmt.Errorf("Unable to marhsal yaml config to JSON '%s': %v", t, err)
This line errors, you need to return the error
```
return fmt.Errorf("Unable to marhsal yaml config to JSON '%v': %v", t, err)
```

Also the %s is for string, where the data for `t` isn't. So you need to either use %v to just print the value, or figure out what in the struct should be returned in the error.

2021-12-08 21:22 UTC, shreddedbacon commented on internal/lagoon/client/_lgraphql/environmentByName.graphql
> -  }
Is this file accidentally deleted? It is used by `internal/lagoon/client/query.go` for the EnvironmentByName query, which is used in imports.

2022-05-09 23:38 UTC, shreddedbacon commented
@timclifford is this still being worked on?

2025-06-11 04:34 UTC, bomoko commented
Closing this up, things have moved on quite dramatically from this time (and hi @timclifford if you see this)

2025-06-11 04:34 UTC, closed without merging