feat: support for identityfiles to select keys from ssh-agent
uselagoon/lagoon-cli pull request #355
Opened 2024-06-13 07:42 UTC by shreddedbacon

# General Checklist

- [ ] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated
- [ ] PR title is ready for inclusion in changelog

This adds support for identityfiles to the config file, which allows for these to select a key if it is found in the ssh-agent
```
lagoons:
    local-k3d:
        identityfiles:
          - /full/path/to/key.pub
```

Additionally, a global `--versbose` flag is added which can be used to print some verbose output to stderr, this could be used elsewhere in the CLI in the future too. In this PR the flag will print which key is being used or if the agent is being used, which can help users with debugging.

# Closing issues

closes #354

2024-06-14 03:52 UTC, smlx commented
Sorry I know I wasn't requested for a review, but I think the public key comparison could be made a bit more robust by using the library parsing functions. Something like this?

 ```go
 var identities []ssh.PublicKey
 for _, idFile := range publicKeyIdentityFiles {
 	keybytes, _ := os.ReadFile(idFile)
 	pubkey, _ := ssh.ParsePublicKey(keybytes)
 	identities = append(identities, pubkey)
 }
 for _, signer := range agentSigners {
 	for _, identity := range identities {
 		if bytes.Equal(signer.PublicKey().Marshal(), identity.Marshal()) {
 			// found a match
 		}
 	}
 }
 ```

2024-06-17 20:14 UTC, rocketeerbkw requested changes
I pasted the wrong path for my public key and got this error:

```golang
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8e5c63]

goroutine 1 [running]:
github.com/uselagoon/lagoon-cli/cmd.publicKey({0xc000267de0, 0x19}, {0x0, 0x0}, {0xc00023d090, 0x1, 0x9fd275?}, 0x5?)
	/home/brandon/dev/amazee-io/lagoon-cli/cmd/login.go:56 +0x8c3
```

I immediately knew it was a spelling error, but not everyone will, can you add a "file exists" check similar to how `-i` has?

Otherwise, this works to use a single key from the ssh-agent as described :tada:

2024-06-25 23:20 UTC, shreddedbacon commented
Updated with file check error handling, so I'll merge this now @rocketeerbkw ?

2024-06-27 22:19 UTC, rocketeerbkw approved these changes
Got an error message for bad file path, and using the specified key still works :+1:

2024-06-27 22:25 UTC, merged